Taller 3-Repaso Matrices
Thomas Jara-202122760
Alejandra Gomez-

In [85]:
import numpy as np


PUNTO 1
Algoritmo multiplicacion matrices

In [86]:
def multiplicacionm(M1,M2):
    resultado=np.zeros((M1.shape[0],M2.shape[1]))
    if M1.shape[1]==M2.shape[0]:
        for fila in range(M1.shape[0]):
            for columna in range(M1.shape[1]):
                 for columnaM2 in range(M2.shape[1]):
                    resultado[fila][columnaM2]+=M1[fila][columna]*M2[columna][columnaM2]
            
        return resultado
    else:
        return print('Las dos matrices no se pueden multiplicar')
    

Primera Parte

Punto a.


In [87]:
M1=np.array([[5,-4,-2],[5,-5,4],[2,5,-4],[-5,4,3],[3,-4,-3]])
M1

array([[ 5, -4, -2],
       [ 5, -5,  4],
       [ 2,  5, -4],
       [-5,  4,  3],
       [ 3, -4, -3]])

In [88]:
M2=np.array([[5],[-2],[-3]])
M2

array([[ 5],
       [-2],
       [-3]])

In [89]:
multiplicacionm(M1,M2)

array([[ 39.],
       [ 23.],
       [ 12.],
       [-42.],
       [ 32.]])

Punto b.

In [90]:
M1=np.array([[0,-1,-1,3],[5,-5,-2,2],[1,0,4,5]])
M1

array([[ 0, -1, -1,  3],
       [ 5, -5, -2,  2],
       [ 1,  0,  4,  5]])

In [91]:
M2=np.array([[0,-3],[-2,-1],[3,-3]])
M2

array([[ 0, -3],
       [-2, -1],
       [ 3, -3]])

In [92]:
multiplicacionm(M1,M2)

Las dos matrices no se pueden multiplicar


Punto c.

In [93]:
M1=np.array([[2,-5,5,1],[5,2,-7,-6],[-6,-1,7,-4],[5,4,1,-5]])
M1

array([[ 2, -5,  5,  1],
       [ 5,  2, -7, -6],
       [-6, -1,  7, -4],
       [ 5,  4,  1, -5]])

In [94]:
M2=np.array([[0,4,-7,1,-6],[-1,-6,-5,1,1],[2,-1,-6,5,-5],[-3,-6,6,3,5]])
M2

array([[ 0,  4, -7,  1, -6],
       [-1, -6, -5,  1,  1],
       [ 2, -1, -6,  5, -5],
       [-3, -6,  6,  3,  5]])

In [95]:
multiplicacionm(M1,M2)

array([[ 12.,  27., -13.,  25., -37.],
       [  2.,  51., -39., -46., -23.],
       [ 27.,  -1., -19.,  16., -20.],
       [ 13.,  25., -91.,  -1., -56.]])

Segunda Parte
Demuestre que la multiplicacion no es conmutativa utilizando dos matrices cuadradas.

In [96]:
n=3
#n es la dimension de la matriz cuadrada

def matriz_random(n):
    #Crea una matriz con valores al azar
    Matriz=np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            Matriz[i][j]=np.random.randint(20)
            #La funcion random.randint(a) escoge un valor entero al azar de 0 hasta a
    return Matriz
M1=matriz_random(n)
M2=matriz_random(n)   

[[ 2. 17.  6.]
 [ 3.  3. 15.]
 [18. 18.  5.]]
[[ 0. 14. 15.]
 [18. 16. 16.]
 [ 7. 11. 11.]]


In [97]:
if np.array_equal(multiplicacionm(M1,M2),multiplicacionm(M2,M1)):
    print('La multiplicacion de matrices es conmutativa')
else:
    print('La multiplicacion de matrices no es conmutativa')

La multiplicacion de matrices no es conmutativa


Segunda parte: Reduccion Gaussiana


Ax=b

Algoritmo de Reduccion Gaussiana: Jacobi

In [120]:
def Jacobi(A,b,x0,itmax=1000,tolerancia=1e-14):
    
    x = x0.copy()
    u = x.copy()
    sumk = x.copy()
    
    residuo = np.linalg.norm( np.dot(A,x) - b)
    
    #print(residuo)
    
    it = 0
    
    while residuo >= tolerancia and it < itmax:
        
        
        u[:] = 0
        sumk[:] = 0.
        
        for i in range(A.shape[0]):
            for j in range(A.shape[1]):
                if i != j:
                    sumk[i] += A[i,j]*x[j]
            #print(sumk)
        
            u[i] = (b[i] - sumk[i])/A[i,i]
        
        
        x = u.copy()
        
        #print(x,residuo)
        # Norma infinita
        residuo = np.max(np.abs(np.dot(A,x) - b))
        # Norma griega
        #residuo = np.linalg.norm( np.dot(A,x) - b)
        
        it += 1
        
        if residuo > 1000:
            print('No calculable con Jacobi')
            x[:] = 0.
            break
        
    return x,it



Punto a

In [133]:
A=np.array([[3.,1.,-1.],[1.,-2.,1.],[4.,-1.,1.]])
b=np.array([2.,0.,3.])

In [114]:
np.linalg.solve(A,b)

array([0.71428571, 0.85714286, 1.        ])

In [134]:
Jacobi(A,b,np.array([0.,0.,0.]))

No calculable con Jacobi


(array([0., 0., 0.]), 37)

Punto b

In [107]:
A2=np.array([[1,1,1],[4,-8,0],[0,-8,10]])
b2=np.array([0,6,0])

Se realizo un intercambio entre las filas 2 y 3 para que logre funcionar el codigo

In [108]:
Jacobi(A2,b2,np.array([0.,0.,0.]))

(array([ 0.71052632, -0.39473684, -0.31578947]), 259)

In [104]:
np.linalg.solve(A2,b2)

array([ 0.71052632, -0.39473684, -0.31578947])

Punto 3
Valores y vectores propios

In [136]:
def GetT(A):
    
    M,N = A.shape
    
    D = np.zeros((M,N))
    R = D.copy()
    T = R.copy()
    
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            if i == j:
              #  print(A[i,j])
               # print(1./A[i,j])
                D[i,j] = 1./A[i,j]
            else:
                R[i,j] = A[i,j]
    
 #   print(D)
 #   print(R)
    return np.dot(D,R)

In [135]:
Matriz=np.array([[-2,1,0],[1,-2,1],[0,1,-2]])

In [138]:
Values,Vectors = np.linalg.eig(GetT(Matriz))
Values, Vectors

(array([-3.41421356, -2.        , -0.58578644]),
 array([[ 5.00000000e-01,  7.07106781e-01,  5.00000000e-01],
        [-7.07106781e-01, -4.05405432e-16,  7.07106781e-01],
        [ 5.00000000e-01, -7.07106781e-01,  5.00000000e-01]]))